name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'


    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test

    - name: Run cover check
      run: make cover-check
